-- MySQL Script generated by MySQL Workbench
-- Fri Apr 30 15:58:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema backend_2021
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema backend_2021
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `backend_2021` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `backend_2021` ;

-- -----------------------------------------------------
-- Table `backend_2021`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backend_2021`.`movie_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`movie_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backend_2021`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(85) NOT NULL,
  `release_date` INT NOT NULL,
  `release_month` INT NOT NULL,
  `release_year` INT NOT NULL,
  `duration_min` INT NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `description` VARCHAR(425) NOT NULL,
  `status` INT NOT NULL DEFAULT '1',
  `movie_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movies_movie_status1_idx` (`movie_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_movies_movie_status1`
    FOREIGN KEY (`movie_status_id`)
    REFERENCES `backend_2021`.`movie_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backend_2021`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backend_2021`.`show_times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`show_times` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backend_2021`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `time_id` INT NOT NULL,
  `show_times_id` INT NOT NULL,
  `locations_id` INT NOT NULL,
  `movies_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedules_show_times1_idx` (`show_times_id` ASC) VISIBLE,
  INDEX `fk_schedules_locations1_idx` (`locations_id` ASC) VISIBLE,
  INDEX `fk_schedules_movies1_idx` (`movies_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedules_show_times1`
    FOREIGN KEY (`show_times_id`)
    REFERENCES `backend_2021`.`show_times` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedules_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `backend_2021`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedules_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `backend_2021`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backend_2021`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backend_2021`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `role` INT NOT NULL DEFAULT '2',
  `status` INT NOT NULL DEFAULT '1',
  `status_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_users_roles1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `backend_2021`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `backend_2021`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `backend_2021` ;

-- -----------------------------------------------------
-- Placeholder table for view `backend_2021`.`rangkuman_all`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backend_2021`.`rangkuman_all` (`id` INT, `name` INT, `release_date` INT, `release_month` INT, `release_year` INT, `duration_min` INT, `genre` INT, `description` INT, `status` INT, `location` INT, `time` INT);

-- -----------------------------------------------------
-- View `backend_2021`.`rangkuman_all`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `backend_2021`.`rangkuman_all`;
USE `backend_2021`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `backend_2021`.`rangkuman_all` AS select `m`.`id` AS `id`,`m`.`name` AS `name`,`m`.`release_date` AS `release_date`,`m`.`release_month` AS `release_month`,`m`.`release_year` AS `release_year`,`m`.`duration_min` AS `duration_min`,`m`.`genre` AS `genre`,`m`.`description` AS `description`,`ms`.`status` AS `status`,`l`.`location` AS `location`,`st`.`time` AS `time` from ((((`backend_2021`.`movies` `m` join `backend_2021`.`movie_status` `ms` on((`m`.`status` = `ms`.`id`))) join `backend_2021`.`schedules` `s` on((`s`.`movie_id` = `m`.`id`))) join `backend_2021`.`locations` `l` on((`l`.`id` = `s`.`location_id`))) join `backend_2021`.`show_times` `st` on((`st`.`id` = `s`.`time_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
